name: "Dummy pipeline"

run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push:
    branches: [ "develop" ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greeting'
        run: echo "Hello, World!"
